/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.app;

public class App {


    public static void main(String[] args) {
        SampleProducer sampleProducer = new SampleProducer();
        
    }
}
